### ISSUE TITLE
Error running EV3-Touch.py "ImportError: No module named builtins"

### ISSUE THREAD

**Issue by fantauzzi** [DexterInd/BrickPi_Python#78]
cd to directory BrickPi_Python/Sensor_Examples and run
```
} sudo python EV3-Touch.py
Traceback (most recent call last):
  File "EV3-Touch.py", line 24, in <module>
    from BrickPi import *   							#import BrickPi.py file to use BrickPi operations
  File "/home/pi/workspace/BrickPi_Python-master/Sensor_Examples/BrickPi.py", line 47, in <module>
    from builtins import input
ImportError: No module named builtins

```
Output of uname -a is
```
} uname -a
Linux dex 4.4.32-v7+ #924 SMP Tue Nov 15 18:11:28 GMT 2016 armv7l GNU/Linux
```

**Comment by CleoQc** [comment]
Hi. You need to run 
`sudo pip install -U future` 
in a terminal to add the library in question.  It's added already for our Raspbian for Robots so I'm assuming you're running your own OS.

**Comment by fantauzzi** [comment]
Hi! I am running the Raspbian for Robots downloaded from here:
https://drive.google.com/file/d/0B0WChwP4CnLBV2R6VE8yeFF2ZFU/view?usp=sharing
as per instructions reported here:
https://www.dexterindustries.com/howto/install-raspbian-for-robots-image-on-an-sd-card/
I have just re-imaged the micro SD with it, it is a fresh install.
Here the output of uname -a

`Linux dex 4.4.32-v7+ #924 SMP Tue Nov 15 18:11:28 GMT 2016 armv7l GNU/Linux`

Should I use a different image instead?

**Comment by CleoQc** [comment]
And thank you for bringing this to our attention. There's now a PR that will take care of this for others . 
https://github.com/DexterInd/BrickPi_Python/pull/79

**Comment by fantauzzi** [comment]
I downloaded the repo from github as a zip file.
**sudo pip install -U future** resolved the issue. Thanks!

**Comment by CleoQc** [comment]
Great!!! 
Just to be safe, you also need to run 
`python setup.py install`
if you haven't already done so.

**Comment by fantauzzi** [comment]
In the output of pip I see BrickPy is already installed. Do I need to run **python setup.py install** nevertheless? 

```
} pip list | grep BrickPi
BrickPi (0.0.0)

```

**Comment by CleoQc** [comment]
Since your base is Raspbian for Robots, and it's the latest version, you're most likely set and don't need to run it. Apologies again for this hiccup you faced.
